### ISSUE TITLE
Support id as selector

### ISSUE THREAD

**Issue by pke** [kisenka/svg-fill-loader#1]
It would be nice if we could instead use an `id` inside the SVG as parameter like this:

`url(img.svg?fill=red&id=myid)`

**Comment by kisenka** [comment]
@pke done in 0.0.3, use following syntax:

`url(img.svg?fill=red&selector=#myid)`

Also `.class` selector available, and you can combine different selectors with commas:

`url(img.svg?fill=red&selector=#myid, circle)`

**Comment by pke** [comment]
Wow! That was quick. Will test tomorrow. Thanks

**Comment by pke** [comment]
Do you think that this would work with dynamic imports. Like replace the fill colour with a variable? 

```
Import colors from "appcolors"
 url(img.svg?fill=" + colors.main + "&selector=#myid, circle) 
```

Can't test myself atm, cause I don't have access to a dev machine

**Comment by kisenka** [comment]
In javascript - I think no (but [webpack can evaluate expressions in imports](http://webpack.github.io/docs/context.html#parser-evaluation) at compile time). Try it. In CSS/SCSS/LESS/etc - yes:

```scss
// styles.scss
$color: #fff;

.a {background-url: url(image.svg?fill=#{$color})}

```

I can add a testcase to demonstrate this.

**Comment by pke** [comment]
You guessed right, its not working in JS code. Webpack cannot evaluate it properly:

```
const image = require("images/image1.svg?fill=" + COLOR)
```

results in `images ^\.\/image1\.svg\?fill=.*$` output on the webpack build process and of course during runtime the image is not found: `Cannot find module "images"`.

So I have to think of another solution to make this more dynamic.

**Comment by kisenka** [comment]
@pke what are you trying to do?

**Comment by pke** [comment]
I have the colours defined in a separate file. And they depend on a process.env variable.

**Comment by kisenka** [comment]
If your config is a simple javascript file, like:

```js
// colors-config.js
module.exports = {
  color1: '#fff',
  color2: '#fc0'
}
```

you can transform it to SCSS variable/map/list/etc via [node-sass-import-builder](https://github.com/kisenka/node-sass-importer-builder), and then you can import your colors config in SCSS like this `@import "colors-config.js"`. The result will be something like:

```scss
$colors-config: (
  "color1": #fff,
  "color2": #fc0
);
```

and then you can use colors like regular SCSS variable with fill loader:

```scss
@import "colors-config.js";
// $colors-config variable will be available after import statement

.a {
  background-image: url('./image.svg?fill=#{ map_get($colors-config, 'color1') }')
}
```

**Comment by pke** [comment]
Thanks. I don't use css though in my app. I assign the svg to an img src attribute.

**Comment by pke** [comment]
Another thought. Maybe I could chain a text replace loader before using this `svg-fill-loader`.
Something like that: `const image = require("!text-replace!images/image1.svg?fill={COLOR})` 
And the text-replace is configured to replace `COLOR` with a string like `#fff` it read from an external file.

**Comment by kisenka** [comment]
Strictly speaking you don't need additional loader for this:

This is your image.svg:
```svg
<svg><path /></svg>
```

And this how you can fill it in js:
```js
var svg = require('./image.svg?fill={WHITE}').replace('{WHITE}', '#fff');
// => "<svg><path fill="#fff" /></svg>"
```

**Comment by kisenka** [comment]
@pke but of course you can write such loader. For example having this colors config:

_colors.config.js_
```js
module.exports = {
  WHITE: '#ffffff',
  BLUE: '#0000ff',
  RED: '#ff0000'
};
```

You can import it in your custom loader & replace placeholders with real color codes:

_my-loader.js_
```js
module.exports = function(content) {
  // import colors config in loader
  var colorsConfig = require('./colors.config.js');

  var matches = content.match(/\{\w+\}/);
  var result = content;

  if (Array.isArray(matches) && matches[0]) {
    var colorName = matches[0].substr(1, matches[0].length-2);
    var color = colorsConfig[colorName];
    result = content.replace(new RegExp('\{'+ colorName +'\}', 'g'), color);
  }

  return 'module.exports = ' + JSON.stringify(result);
};
```

And then with following import:
```js
var svg = require('!./my-loader!svg-fill!./image.svg?fill={WHITE}')
// => "<svg><path fill="#fff" /></svg>"
```

And please, don't inline loaders requests, use webpack configuration to setup them.
