### ISSUE TITLE
Modify opacity

### ISSUE THREAD

**Issue by Londeren** [kisenka/svg-fill-loader#10]
Howdy!
Is it possible to modify other props, like `opacity` for example?
I'm trying to do 
`icon.svg?fill=#f00&opacity=0.5` but it doesn't work.

**Comment by kisenka** [comment]
@Londeren ola! Do you mean CSS `opacity` option? i.e. `<path style="opacity: 0.5">`?

**Comment by Londeren** [comment]
In my case this is `<g opacity="1">`

**Comment by kisenka** [comment]
Could you tell me more about your use case? Why you couldn't set this property in CSS?

**Comment by Londeren** [comment]
I have an SVG icon that I set as `background-image` and I need a different opacity for icon (for hover, active etc.) and I can't use `opacity: XX;` because this element has inner text
`<div class="icon">Back</div>`. I don't want to use additional wrapper element.

**Comment by kisenka** [comment]
I'd like to keep fill loader as simply as it possible. It responsible just for 1 thing: fill parts of SVG image.
