### ISSUE TITLE
Sample SVG please!!

### ISSUE THREAD

**Issue by juegas** [kisenka/svg-fill-loader#13]
I've got everything set up but no fill happening on my simple SVG with a rect. 

Is there a sample SVG anyone can share

**Comment by kisenka** [comment]
@juegas sorry, I don't understand. What sample SVG you're talking about?

**Comment by juegas** [comment]
@kisenka I'm asking if there is an example project available with setup and sample SVG. 

I've set up my project as prescribed in the readme but I'm getting no fill happening for me. I'm wondering if my SVG is somehow no good, and wanted to see the SVG you used for the gif in the readme. 

thx

**Comment by kisenka** [comment]
@juegas there is no sample project, but I can create some example, good point.

**Comment by kisenka** [comment]
This loader is moved to svg-mixer project and renamed to [svg-transform-loader](https://github.com/kisenka/svg-mixer/tree/master/packages/svg-transform-loader).
