### ISSUE TITLE
Unable to use '#' character in background-image url

### ISSUE THREAD

**Issue by RehanSaeed** [kisenka/svg-fill-loader#18]
When I use the following SASS, where I use a `#` symbol for the fill colour, my background image is not rendered, this leaves me unable to use a SASS variable for the colour:

```
.list-group-item-chevron::after {
  content: '';
  background-image: url("../images/icons/chevron-right.svg?inline&fill=#4b5255");
  background-size: 1rem 1rem;
  height: 1rem;
  width: 1rem;
}
```

The following is output by the loader:

> url("data:image/svg+xml,%3C?xml version='1.0' encoding='utf-8'?%3E %3Csvg width='1792' height='1792' viewBox='0 0 1792 1792' xmlns='http://www.w3.org/2000/svg'%3E %3Cpath d='M1363 877l-742 742q-19 19-45 19t-45-19l-166-166q-19-19-19-45t19-45l531-531-531-531q-19-19-19-45t19-45l166-166q19-19 45-19t45 19l742 742q19 19 19 45t-19 45z'/%3E %3C/svg%3E"#4b5255)

When I remove the `#` before the fill colour, so I use `fill=4b5255` instead, the SVG is rendered sccessfully:

> url("data:image/svg+xml,%3Csvg width='1792' height='1792' viewBox='0 0 1792 1792' xmlns='http://www.w3.org/2000/svg'%3E %3Cpath d='M1363 877l-742 742q-19 19-45 19t-45-19l-166-166q-19-19-19-45t19-45l531-531-531-531q-19-19-19-45t19-45l166-166q19-19 45-19t45 19l742 742q19 19 19 45t-19 45z' fill='4b5255' /%3E %3C/svg%3E")

I am using `svg-url-loader` with the latest `0.0.8` release of `svg-fill-loader` in my CSS and `svg-sprite-loader` with `svg-fill-loader` in my HTML and JavaScript. I have configured Webpack to use the `svg-url-loader` when it sees `inline` in the SVG's URL using the webpack `resourceQuery` feature. Here is my CSS:

```
.icon1 {
  /* SVG will be inlined in CSS */
  background-image: url('./foo.svg?inline&fill=red');
}

.icon2 {
  /* default way - build a sprite and use SVG fragment identifiers */
  background-image: url('./foo.svg&fill=red');
}
```

Here is my Webpack config:

```
{
  module: {
    rules: [
      ...
      {
        test: /.svg$/,
        oneOf: [
          {
            resourceQuery: /inline/, 
            use: [
              'svg-url-loader',
              'svg-fill-loader',
            ],
          },
          {
            use: [
              {
                loader: 'svg-sprite-loader',
                options: {
                  esModule: false,
                  extract: true,
                },
              },
              'svg-fill-loader',
            ],
          },
        ],
      },
    ]
  }
}
```

**Comment by kisenka** [comment]
Do you read the docs section [Using with css-loader](https://github.com/kisenka/svg-fill-loader#using-with-css-loader)?

**Comment by RehanSaeed** [comment]
Apologies, did no spot that.
