### ISSUE TITLE
Recommended loader configuration accepts invalid svg extensions

### ISSUE THREAD

**Issue by notpeelz** [kisenka/svg-fill-loader#20]
The recommended loader configuration uses a (RegExp) pattern that accepts non-svg extensions, e.g. `.svg.js` or `.svgaaaaa`

FWIW, you should use the same pattern in both config examples (the Webpack 2.x one differs)

Proposed fix
------------------
```js
module.exports = {
  module: {
    loaders: [
      {
        test: /\.svg(\?.*)?$/, // This pattern doesn't accept invalid svg extensions
        // ...
      }
    ]
  }
}
```

Source (from `README.md`)
-----------------------------------------
```js
module.exports = {
  module: {
    loaders: [
      {
        test: /\.svg((\?.*)?|$)/,
        loaders: [
          'svg-url-loader', // or url-loader
          'svg-fill-loader?selector=path,circle' // `selector` option will be used for all images processed by loader
        ]
      }
    ]
  }
}
```

**Comment by kisenka** [comment]
This loader is moved to svg-mixer project and renamed to [svg-transform-loader](https://github.com/kisenka/svg-mixer/tree/master/packages/svg-transform-loader).
@LouisTakePILLz thanks, I've update the [README](https://github.com/kisenka/svg-mixer/tree/master/packages/svg-transform-loader#webpack-config).
