### ISSUE TITLE
does not work with the resolve-url-loader

### ISSUE THREAD

**Issue by webroru** [kisenka/svg-fill-loader#3]
I use the resolve-url-loader for define correct path to svg (when svg is locate not in the same folder with scss). In this case the svg-fill-loader does not see svg.

scss:
```
.twitter {
    background-image: url('../icons/twitter.svg?fill=red');
  }
```

My webpack config:

```
module.exports = {
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style', ['css', 'resolve-url', 'sass?sourceMap']),      },
      {
        test: /\.svg(\?fill=)?$/,
        loaders: ['url', 'svgo', 'svg-fill'],
      },
    ],
  },
}
```
Temporary solution for me is remove the resolve-url-loader and replace path to svg as url('**.**/icons/twitter.svg?fill=red') (with one dot leading). Perhaps there is more correct decision.

**Comment by webroru** [comment]
oh my carelessness. I decided it.

 just add to the webpack config:
```
 resolveUrlLoader: {
    keepQuery: true,
  },
```

**Comment by kisenka** [comment]
No problem :)
Is this loader useful for you?

**Comment by webroru** [comment]
absolutely! brilliant loader!
