### ISSUE TITLE
Proper Webpack (2) configuration

### ISSUE THREAD

**Issue by Tarpsvo** [kisenka/svg-fill-loader#5]
Hey.

This is a question.

How would a proper Webpack 2 configuration look like for this plugin? I managed to get it properly working with the following rule:

```shell
{ test: /\.(svg)/, loaders: ['url-loader', 'svg-fill-loader'] }
```

But for correctness sake, I would like to avoid passing regular `.svg` files, without the `fill` parameter to the `svg-fill-loader`. My logic said that the rule should be the following, but it did not work.

```shell
{ test: /\.(svg\?fill=)/, loaders: ['url-loader', 'svg-fill-loader'] },
{ test: /\.(svg)$/, loader: 'url-loader' }
```

Where am I going wrong?

Thank you.

**Comment by kisenka** [comment]
Hey @Tarpsvo. I am not sure, but looks like resource part of query was dropped in [webpack 2](https://gist.github.com/sokra/27b24881210b56bbaff7#loaders-configuration):
> ...the query string is no longer included for matching.

That means that this loader wouldn't work with webpack 2. I am sorry.

**Comment by Tarpsvo** [comment]
Word. It's working for me, with the first example I provided. I guess the query string is only not included for matching, but it's still available.

**Comment by kisenka** [comment]
As you said - query string is ignored in matching, so there is no way to separate SVGs with query string from usual SVGs in Webpack 2. But it's safe to pass all SVGs through loader, if no fill param presented it [just returns original source](https://github.com/kisenka/svg-fill-loader/blob/master/test/loader.test.js#L41).
Thank you for your feedback. I am glad to serve the Emperor, comrade!
